# Generated by Django 4.2.3 on 2023-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contastant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=40)),
                ('c_email', models.EmailField(max_length=30)),
            ],
        ),
    ]
