# Generated by Django 4.2.6 on 2023-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Index', models.CharField(max_length=3)),
                ('Rating', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pupil', models.IntegerField()),
                ('Specialist', models.IntegerField()),
                ('Expert', models.IntegerField()),
                ('Candidate_Master', models.IntegerField()),
                ('Master', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Index', models.CharField(max_length=3)),
                ('Rating', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('handle', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Index', models.CharField(max_length=3)),
                ('Rating', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Index', models.CharField(max_length=3)),
                ('Rating', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Index', models.CharField(max_length=3)),
                ('Rating', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
